### ISSUE TITLE
Colombia page parameter - can this be logged anywhere somehow?

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher-scrape#112]
I'm concerned that this means we could end up with data files that only have half of Colombia's data and we don't record that fact anywhere. Later, we may mistake these data files for the complete load which could lead to inaccurate MEL reports, etc.

Maybe if this parameter is used, it could be marked as a sample run?

This may also be a use for https://github.com/open-contracting/kingfisher/issues/311

**Comment by jpmckinney** [comment]
I added this as a requirement to #346.
