### ISSUE TITLE
Deploy Tokens

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher-scrape#141]
https://github.com/open-contracting/kingfisher-scrape/commit/744cc60a34e444173383908c58795b32dd4bc704 adds three new tokens that we need to make sure are deployed properly.

I have set up the Salt scripts for the two hacienda tokens, but I did not have the other one.

What needs to be done:

*  get a token for kingfisher_paraguay_dncp_request_token
*  add this token to pillar/private/ocdskingfisher_pillar.sls , to the existing variable (someone from OCDS needs to do this)
*  deploy to live server
*  restart scrapyd - see https://kingfisher-scrape.readthedocs.io/en/latest/use-hosted.html#stopping-and-starting-scrapyd

**Comment by yolile** [comment]
I sent to @odscjames and David R. the access token for paraguay dncp

**Comment by odscjames** [comment]
I have done the first two points, got token, and put into pillar/private/ocdskingfisher_pillar.sls. It can be seen on the dev server now.

**Comment by odscjames** [comment]
I have now deployed to the live server.

However, I couldn't restart scrapy as there is already a job running (for 3 days!). When that job is finished, someone should

-  restart Scrapyd https://kingfisher-scrape.readthedocs.io/en/latest/use-hosted.html#stopping-and-starting-scrapyd
- Upload new versions of spiders using scrapyd-deploy https://kingfisher-scrape.readthedocs.io/en/latest/use-hosted.html#deploying-latest-spiders

**Comment by odscjames** [comment]
Scrapyd has now been restarted
