### ISSUE TITLE
Could FILES_STORE be set from an environment variable?

### ISSUE THREAD

**Issue by romifz** [open-contracting/kingfisher-scrape#144]
Could FILES_STORE take its value from an environment variable, and default to "data" if the variable does not exists? It will be consistent with other Kingfisher configurations.

@odscjames

**Comment by odscjames** [comment]
Yes, that makes sense.

**Comment by jpmckinney** [comment]
Can use same approach for #249.

**Comment by jpmckinney** [comment]
@romifz Would this just be for local development?

**Comment by romifz** [comment]
@jpmckinney I proposed this so all kingfisher-scrape's configurations can be set the same way (as KINGFISHER_API_URI and KINGFISHER_API_KEY, which I can't find in the documentation now). 

It could be used for local development, but my thinking is that others that may reuse kingfisher shouldn't need to edit source files unless they want to change kingfisher's behavior.

**Comment by jpmckinney** [comment]
They'll be added back to the docs in #297 (I copied the docs there for now).

In my experience editing a `settings.py` file once is much easier than setting multiple environment variables in each work session. See #298 to discuss.
