### ISSUE TITLE
Add Mexico SCT (Red Compartida) scraper

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-scrape#148]
Low priority as not expected to continue publishing.

https://datos.gob.mx/redcompartida/

**Comment by odscjames** [comment]
That link 404's - is that as expected now?

**Comment by aguilerapy** [comment]
In this link https://datos.gob.mx/busca/dataset/proceso-de-contratacion-del-proyecto-de-la-red-compartida if you try to download the json file, redirects us to a file that does not exist https://drive.google.com/uc?export=download&id=0B5wc002kIlpheVV3a29YbFJaSUU

**Comment by jpmckinney** [comment]
Given that they no longer publish, I don't expect the link to be fixed, so closing.
