### ISSUE TITLE
Add Dhangadhi scraper

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-scrape#149]
See JSON downloads at https://ims.susasan.org/dhangadhi#downloads

This is a vendor's pre-production URL.

cc @duncandewhurst

**Comment by odscjames** [comment]
Do we know a priority for this one?

**Comment by odscjames** [comment]
I have done a pull request with this one, where the 2 JSON URL's are just hard coded for now. 

Do we know if they are going to add extra URL's regularly? If so, we'll need to get the initial web page and do some HTML scraping to find links.

**Comment by duncandewhurst** [comment]
The current files are annual files (Nepal has a different calendar), so reasonable to expect that there will be new files once a year.

**Comment by jpmckinney** [comment]
I figure we should scrape the page with the links to the JSON URLs, then close the issue.

**Comment by duncandewhurst** [comment]
The links [seem to have disappeared](https://ims.susasan.org/dhangadhi/#downloads):

> No OCDS Files generated for this municipality.

I'll check with the publisher on why this is.

**Comment by jpmckinney** [comment]
Maybe it was intermittent? I see links at that URL.

**Comment by duncandewhurst** [comment]
Ah, interesting. The original URL in this issue still works, but the downloads are no longer discoverable from the IMS website (which is how I tried to get there yesterday). The publisher said:

> Regarding the OCDS download links in IMS Dhangadhi page, there was one
known issue, new updates will be deployed by Monday.

**Comment by jpmckinney** [comment]
If you interact with the website while the loading animation is on, it seems that the downloads don't appear when clicking "Downloads" in the sidebar. When I wait, they appear.

**Comment by odscjames** [comment]
Looking at network requests, it looks like https://admin.ims.susasan.org/api/static-data/dhangadhi gives you the data - you can look for the elements in fiscal_years which have is_current = false and get JSON links from there. That might save us some screen scraping within a Javascript app, which I wasn't looking forwards to.

However, if you go to the URL for the is_current=true one, you get redirected to an login page - https://admin.ims.susasan.org/ocds/json/dhangadhi-2076-77.json - any ideas?

**Comment by jpmckinney** [comment]
That URL no longer renders a login page, so this is unblocked.
