### ISSUE TITLE
Add Buenos Aires scraper

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-scrape#152]
https://data.buenosaires.gob.ar/dataset/buenos-aires-compras

**Comment by odscjames** [comment]
Do we know a priority for this one?

**Comment by jpmckinney** [comment]
I created a board with all "new scraper" issues, and prioritized them all. This and #149 are "Medium" priority: https://github.com/open-contracting/kingfisher-scrape/projects/1

**Comment by odscjames** [comment]
I think this is done? https://github.com/open-contracting/kingfisher-scrape/blob/master/kingfisher_scrapy/spiders/buenos_aires.py

**Comment by jpmckinney** [comment]
Yup, that closes the issue.
