### ISSUE TITLE
Clean up non-PR branches

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-scrape#16]
@rhiaro @BibianaC @odscjames Can you either open a PR for your [branches](https://github.com/open-contracting/kingfisher-scrape/branches/all), or delete them if they are no longer relevant (testing branches, etc.)?

**Comment by odscjames** [comment]
Already noted this needs cleaning up https://github.com/open-contracting/kingfisher/issues/281

**Comment by odscjames** [comment]
The only branch I'm responsible for is "master-noframework" which I'd like to leave for a bit for testing, tho it will never be merged to master! Assigning to others for rest.

**Comment by jpmckinney** [comment]
@BibianaC @rhiaro @yolile Pinging again.

@odscjames You have some new, non-PR branches as well.

**Comment by yolile** [comment]
I have no test branches

**Comment by jpmckinney** [comment]
@yolile Thanks. Can you look at yours on the other repo? https://github.com/open-contracting/kingfisher/branches/all

**Comment by BibianaC** [comment]
@jpmckinney done!

**Comment by odscjames** [comment]
Have removed my dead branches
