### ISSUE TITLE
chile_compra_records sample broken

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher-scrape#172]
Found when doing #168

The URL https://apis.mercadopublico.cl/OCDS/data/listaA%C3%B1oMes/2017/10 returns a 200 HTTP code but the body has some JSON with a 400 error message!

**Comment by odscjames** [comment]
I've just rechecked that URL, and it now returns a HTTP 404.

**Comment by yolile** [comment]
Should be fixed now by #219
