### ISSUE TITLE
Documentation for kf-scrape standalone users

### ISSUE THREAD

**Issue by robredpath** [open-contracting/kingfisher-scrape#174]
During the Researchers/Academics data use training in Nottingham in June 2019, we heard that kf-scrape might be a useful tool for people who want to obtain bulk data for their own analysis. However, it's a cmdline tool, and cmdline skills aren't necessarily common among the people who would benefit from its functionality. 

Some documentation to guide people through the process, and to make explicit assumptions about using the cmdline, would be helpful in such cases.

**Comment by jpmckinney** [comment]
Related: https://github.com/open-contracting/kingfisher/issues/333
