### ISSUE TITLE
Add Uruguay records scraper

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-scrape#180]
https://www.gub.uy/agencia-compras-contrataciones-estado/datos-y-estadisticas/datos/open-contracting

**Comment by odscjames** [comment]
I can't find a way to get the records. The Google Translated page does mention records, but the URL seems to point me to releases. 

@yolile @romifz Can one of you help here and see if you can just describe the route to take to get records?

**Comment by robredpath** [comment]
@odscjames should this be linked from a Trello card?
