### ISSUE TITLE
Update or Replace Moldova Scraper

### ISSUE THREAD

**Issue by mrshll1001** [open-contracting/kingfisher-scrape#192]
We need to run a scrape for Moldova but based on communications with them we understand that the scraper needs updating or replacing. The old endpoints have been superseded with the following:

* budgets: https://public.mtender.gov.md/budgets
* plans: https://public.mtender.gov.md/tenders/plan
* tenders: https://public.mtender.gov.md/tenders

It is currently unclear as to whether or not the old data is available through these new endpoints. I will check with them and report back through here with a comment.

**Comment by mrshll1001** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Updating or Replacing Moldova Scraper](https://trello.com/c/rJOBuka8/80-updating-or-replacing-moldova-scraper)

**Comment by mrshll1001** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Updating or Replacing Moldova Scraper](https://trello.com/c/rJOBuka8/80-updating-or-replacing-moldova-scraper)

**Comment by mrshll1001** [comment]
Apparently I misunderstood the original response, there are actually *two, distinct,* implementations. One still uses the current endpoints in the scraper, but are not currently working at the moment.

The second implementation uses the endpoints noted here:

* budgets: https://public.mtender.gov.md/budgets
* plans: https://public.mtender.gov.md/tenders/plan
* tenders: https://public.mtender.gov.md/tenders

There still isn't clarification as to whether these implementations have differing scopes of data but if there's two implementations that would suggest having a new scraper for the second implementation.

I'll also chase up the developers of the first implementation to clarify what the technical issues are with the endpoints we use currently

**Comment by odscjames** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Look into stopping HTTPS crawlers hitting real sites and generating errors](https://trello.com/c/tdbyqzFV/93-look-into-stopping-https-crawlers-hitting-real-sites-and-generating-errors)

**Comment by odscjames** [comment]
Each of the 3 end points just returns a list of OCID's.

Q1) With an OCID, where do we go to get the actual data?

Q2) Each end point returns exactly 100 records. Is there paging - if so how do we access it?

**Comment by jpmckinney** [comment]
Put the OCID at the end of the URL, e.g. https://public.mtender.gov.md/budgets/ocds-b3wdp1-MD-1539787491579

**Comment by jpmckinney** [comment]
To paginate, take the `offset` value in the response, and put it as a query parameter, e.g. https://public.mtender.gov.md/budgets?offset=2018-10-19T13:12:56.000Z

**Comment by mrshll1001** [comment]
DR has written this scraper in [pr 194](https://github.com/open-contracting/kingfisher-scrape/pull/194). We had a chat about potential data quality issues coming out, but pragmatically there was some weird API behaviour worth noting too.

The `/tenders/plans` endpoint appeared to return exactly the same data as the `/tenders` endpoint except that when given an OCID parameter it returned an error message. It may be that `/tenders/plans` just lists a subset of `/tenders` but this isn't clear.

**Comment by odscjames** [comment]
> The /tenders/plans endpoint appeared to return exactly the same data as the /tenders endpoint except that when given an OCID parameter it returned an error message. It may be that /tenders/plans just lists a subset of /tenders but this isn't clear.

Just noting this isn't documented in the scraper itself, and the commit doesn't have an link to this issue for people to find - can we leave this issue open and just add the above as a comment to the scraper for future folk? Thanks.

**Comment by odscjames** [comment]
This has now been commented - so closing.
