### ISSUE TITLE
High priority: Add uk_fts scraper

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/kingfisher-scrape#205]
Add a scraper for the UK's FTS test environment ([API documentation](https://enoticetest.service.xgov.uk/apidocumentation/1.0/GET-ocdsReleasePackages))

The base URL is: `https://enoticetest.service.xgov.uk/api/1.0/ocdsReleasePackages`

Pagination works by taking the `nextCursor` value from the API response and passing it as the `cursor` parameter until `nextCursor` = 'null', e.g.  `https://enoticetest.service.xgov.uk/api/1.0/ocdsReleasePackages?cursor=bmV4dEN1cnNvcj0xNTMxNTg=`

The API currently returns data in the following structure:

```json
{
   "results": [
      {
         "ocdsReleasePackage": {
            "releases": [
               {
                  ...ocds release...
               }
            ]
         }
      },
      {
         "ocdsReleasePackage": {
            "releases": [
               {
                  ...ocds release...
               }
            ]
         }
      }
   ]
}
```

**Comment by jpmckinney** [comment]
Can we not send each value of the `ocdsReleasePackage` key over to Process? It's okay for us to lose all their other metadata.

**Comment by odscjames** [comment]
Just because we send data to process doesn't mean process has to save it - the other metadata will be lost :-)

I would suggest another file type is best; it means each URL data will be sent in one request to process and process has more flexibility in the future for how it handles them. It also will reduce the number of requests between scrape and process by 1000 times.

**Comment by jpmckinney** [comment]
Maybe instead of each time creating a new type like `release_package_in_ocdsReleasePackage_in_list_in_results`, the spider can instead pass a JSON path as a further parameter, indicating the root path of the packages? OCDS Kit has a `--root-path` option just for this.

**Comment by odscjames** [comment]
I was wondering about this too and have made https://github.com/open-contracting/kingfisher-process/issues/209 to make sure this point is not forgotten

**Comment by odscjames** [comment]
Deployed and running

**Comment by jpmckinney** [comment]
Can this be closed?

**Comment by duncandewhurst** [comment]
Yes, we'll need to update the scraper once they have addressed our feedback on the structure of the API response, but no need to keep it open now

**Comment by odscjames** [comment]
https://trello.com/c/tnh3wWHF/127-high-priority-add-ukfts-scraper
