### ISSUE TITLE
Write scrapers for new Paraguay API

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/kingfisher-scrape#218]
This is a high priority as OCP need to check the API is working so they can sign-off the project.

The documentation is here: [http://beta.dncp.gov.py/datos/api/v3/doc/](http://beta.dncp.gov.py/datos/api/v3/doc/)

It looks to use the same token/authentication model as the existing Paraguay API.

To get all the data, I think we need to write scrapers for only the following endpoints:

* /ocds/record/
* /ocds/releases/ocid

If I understood correctly, the list of ocids to pass as parameters can be obtained from the csv files here: [https://www.contrataciones.gov.py/datos/convocatorias](https://www.contrataciones.gov.py/datos/convocatorias)

@yolile - please confirm I got all the above correct, thank you!

**Comment by duncandewhurst** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Write scrapers for new Paraguay API](https://trello.com/c/QfFio5Jf/157-write-scrapers-for-new-paraguay-api)

**Comment by yolile** [comment]
You can use the service
http://beta.dncp.gov.py/datos/api/v3/doc/search/processes
To list all the existing processes (only 2018 and 2019 are loaded for now)
and use the field compiledRelease.ocid to get fue full releases and records
with the two services that you already mentioned.
Also the token now expires after 15 minutes always, no with a certain
number of requests.

**Comment by duncandewhurst** [comment]
@yolile suggested that @romifz can write the scraper

**Comment by jpmckinney** [comment]
Noting that there are some issues mentioned in CRM 4864, though the scraper was updated in #227.

**Comment by odscjames** [comment]
Finding: The Proxy was working on IPv4 only - I added IPv6 support. It now works for both HTTP and HTTPS.

> 
> root@process1 ~ # curl -x http://staging.docs.opencontracting.uk0.bigv.io:8888  http://example.com
> <!doctype html>
> <html>
> <head>
>     <title>Example Domain</title>
> .............
> 


> root@process1 ~ # curl -x http://staging.docs.opencontracting.uk0.bigv.io:8888  https://www.google.com
> <!doctype html><html itemscope="" itemtype="http://schema.org/WebPage" lang="en-GB"><head><meta content="text/html; charset=UTF-8" http-equiv="Content-Type"><meta content="/images/branding/googleg/1x/googleg_standard_color_128dp.png" itemprop="image"><title>Google</title><script nonce="Q7pHyRImtRzW8C2ECltt2Q==">(function(){window.google={kEI:'mJEUXuKwMquelwS_rInIBA',kEXPI:'0,2020 ..........

**Comment by odscjames** [comment]
I have merged in @romifz Proxy code, tested on live, and added a docs section.

I will now hand this back to @romifz - When I run this on the live server I get 

>    2020-01-07 16:04:27 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET http://beta.dncp.gov.py/datos/api/v3/doc/search/processes?fecha_desde=2010-01-01> (failed 2 times): 500 Internal Server Error

**Comment by robredpath** [comment]
@romifz is this done? Can we close this?

**Comment by romifz** [comment]
Yes we can - I just ran the scraper using scrapyd in the server and everything looks good. :)
