### ISSUE TITLE
Update docs to use Scrapy terminology

### ISSUE THREAD

**Issue by robredpath** [open-contracting/kingfisher-scrape#247]
We're quite committed to Scrapy now, and if we did move away then the docs would require significant work. 

For the same reasons as outlined in #228 we should update the docs to no longer refer to scrapers, but spiders (for example).

**Comment by robredpath** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update kf-scrape docs to use Scrapy terminology](https://trello.com/c/uFJxWATW/179-update-kf-scrape-docs-to-use-scrapy-terminology)

**Comment by jpmckinney** [comment]
There are a few instances of 'scrape' in code comments, but these aren't serious (few people will ever read them, and no end users will), and can be fixed whenever we next edit those files.

The CLI commands use 'scrape', but we can rename these as part of #261, which will involve a greater amount of rework if pursued.
