### ISSUE TITLE
Do we need kingfisher.collectioninfo and kingfisher-finished.collectioninfo?

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-scrape#275]
If we do `self.crawler.stats.set_value('kingfisher/source', self.name)`, etc. then this information will instead appear in the `*_report.log` files, which I think is fine, and takes advantage of parts of the Scrapy framework, rather than inventing our own solution.

**Comment by jpmckinney** [comment]
@yolile @romifz @duncandewhurst @pindec @mrshll1001 Please contribute your thoughts, including whether you've ever used the kingfisher.collectioninfo or kingfisher-finished.collectioninfo files that are written for each crawl.

**Comment by yolile** [comment]
I didn't even know that those files exist, so I never used them

**Comment by duncandewhurst** [comment]
I don't use them!

**Comment by romifz** [comment]
I neved used then neither.

**Comment by odscjames** [comment]
I put these and the *.fileinfo files in.

The purpose was so we could write a better local-load/restore system at some point.

Currently, if you have a bunch of files on disk from a year ago and you want to load them back into the system you can, but you have to manually work out and pass various attributes. You have to pass the type of the files or it totally breaks.  Some information, like the original URL of the file is lost and can't be restored. 

I quickly threw these files in when I was changing something else with the system with the idea that at some point we could write a much better restore function; you'd simply point it at a directory, and it would be able to restore everything else including various bits of meta information.

Its true some of this information (all of it, possibly?) should appear in the log of the scrape, but those logs aren't currently stored with the files so they could easily be lost.  Also getting it to dump extra info alongside makes for much easier reading later than writing something to parse a log reliably and error free.

**Comment by jpmckinney** [comment]
This issue is just about the collectioninfo files, not the fileinfo files (which can be discussed separately in #307).

As noted in the PR #290:

> The source, data version, and sample status are already represented in the file path (`<source>[_sample]/<data_version>`). The fact that the spider finished (previously represented by the existence of `kingfisher-finished.collectioninfo`) is already represented in the crawl log.

> After this PR, the note and end time won't be represented anywhere on the filesystem, but, from Kingfisher Scrape's perspective, I don't think we care that much about notes (most are just who started the scrape) or the end time (#275 suggested they could just be recorded as crawl stats). 

> The note and end time are still sent to Kingfisher Process, where we do care about them.

So, I don't know that these files have a use case that is both (1) important and (2) isn't served by the file path. Restoring old data is expected to be such a rare occurrence that requiring an analyst to pass the source, etc. parameters (based on reading the file path) isn't too great a demand.

This discussion does raise the need to backup the scraper logs, which contain other relevant information that we'd want to save. New issue: #308

**Comment by robredpath** [comment]
Two questions:
- Do we need to look at what uses there are around what people want to know about the status of scrapers / how scrapes went? https://github.com/open-contracting/kingfisher-scrape/issues/193 was resolved last year, but is there more we can/want to do there?
- Is there an interaction here with restoring from backups? I'm starting to collect requirements around backups (and therefore also, restoring) for https://trello.com/c/ZApmMlpU/155-talk-to-analysts-odsc-cds-ocp-about-how-much-data-on-kingfisher-server-should-be-backed-up and so I'm interested in what @odscjames said that " Some information, like the original URL of the file is lost and can't be restored.". Do we need to either ensure that this information is kept in the log (and 'how to extract it' be documented?) or back up in such a way that the situation that's envisaged ("a bunch of files on disk from a year ago") isn't a one that's likely to occur either in regular work or in a backup-restore scenario?

**Comment by jpmckinney** [comment]
> Some information, like the original URL of the file is lost and can't be restored.

That specific comment relates to #307 (which is blocked for that reason), so not part of this issue.

We should discuss our needs around backup/restore as part of that Trello card, but I don't see a scenario where we need the two files discussed in this issue.

**Comment by jpmckinney** [comment]
Closed by #290. Continued in referenced Trello card, #307, #308.
