### ISSUE TITLE
Don't use requests in any spiders

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-scrape#293]
Instead, yield [Request](https://docs.scrapy.org/en/latest/topics/request-response.html#request-objects)s with the `callback` parameter, as usual when using Scrapy… This affects:

* [x] kenya_makueni
* [x] paraguay_base
* [x] paraguay_hacienda
* [x] quien_es_quien
* [x] uganda_releases

**Comment by romifz** [comment]
In `paraguay_base` we use requests to get API tokens. If we want to use scrapy requests, they should be created with the highest priority possible (so they get to the top of scrapy's request queue).

**Comment by jpmckinney** [comment]
@romifz Sure, we can set `Request(…, priority=1000)`: https://docs.scrapy.org/en/latest/topics/request-response.html#scrapy.http.Request

**Comment by jpmckinney** [comment]
@yolile I think this is still open for paraguay_base and hacienda.
