### ISSUE TITLE
Do we need the scrape-report command?

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-scrape#294]
The command:

    python ocdskingfisher-scrape-cli scrape-report scrapyd/logs/kingfisher/spider_name/6487ec79947edab326d6db28a2d86511.log

is essentially the same as:

    tac scrapyd/logs/kingfisher/spider_name/6487ec79947edab326d6db28a2d86511.log | grep -B99 statscollectors | tac

1. Do any analysts use this command?
2. My assumption is that analysts will simply copy-paste the sample command from the docs (I know that I can't remember `python ocdskingfisher-scrape-cli scrape-report …`). Is there any strong preference for copy-pasting the first command above, rather than the second?

@romifz @yolile @pindec @duncandewhurst @mrshll1001

**Comment by pindec** [comment]
1. I haven't used it because I tend to look at the logs in the front end.
2. In general, I first do CTRL-R to reverse search what I'm trying to do, then if that fails, I'll look at the docs to copy and paste commands. For the former, keeping related commands under ocdskingfisher-scrape-cli would be helpful.

**Comment by romifz** [comment]
1. I have never used this command, I usually just open the logs using less.
2. I have no preferences.

**Comment by yolile** [comment]
1. I have never used this command, I usually just open the logs using tail.
2. I have no preferences.

**Comment by jpmckinney** [comment]
Okay, I'll remove the command when I close #295 (which requires server configuration changes) and I'll update the docs accordingly. With #295, we'll have removed the entire CLI interface.

**Comment by jpmckinney** [comment]
Closed by https://github.com/open-contracting/kingfisher-scrape/commit/3b6f1f4fe07b373be4977250a84c187c249cfeaa
