### ISSUE TITLE
Replace the log-dir-scrape-report command with a simple shell script

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-scrape#295]
`find ../scrapyd/logs/ -type f -name "*.log" -not -name "*_report.log" -exec sh -c 'if [ ! -f {}.stats ]; then result=$(tac {} | head -n99 | grep -m1 -B99 statscollectors | tac); if [ ! -z "$result" ]; then echo "$result" > {}.stats; fi; fi' \;`

… does the same thing, and is much less code to maintain. (`-not -name "*_report.log"` can be removed if we stop generating `*_report.log` files; this command generates `*.log.stats` files.)

If we can remove scrape-report as in #294, then we can delete all CLI-related files and docs, ~~and close #261~~.

Preferably, this shell script would be stored and deployed by the `deploy` repo, rather than maintained in this repo, as I don't consider it to be of broader interest to potential re-users.

**Comment by jpmckinney** [comment]
Noting that ocdskingfisherscrape.sls in the deploy repo would have to use this shell script instead of the log-dir-scrape-report command.

**Comment by odscjames** [comment]
For context, I did this as Python with the idea of expansion; currently only basic info is pulled out of the log report, but I can easily see in the future that it would be good to pull more info out. Also, I can see what info we want and how we pull this information out varying per scraper - for instance for the scrapers that have authentication tokens, being able to report on any specific problems there. I thought that maybe in the future we could add extra methods to the current scraper classes, thus keeping the scraper code and the specific code to report on that scraper together.

**Comment by jpmckinney** [comment]
I think we can use https://github.com/my8100/logparser instead. See comments starting from https://github.com/open-contracting/kingfisher-scrape/issues/198#issuecomment-583454134

Rather than a CLI script that generates files, I figure a better solution would extract relevant information (using logparser) and present it in the dashboard envisioned in https://github.com/open-contracting/kingfisher/issues/327

**Comment by jpmckinney** [comment]
For posterity, if we want to re-introduce additional commands, we should use the facility that Scrapy already provides: https://docs.scrapy.org/en/latest/topics/commands.html#custom-project-commands
