### ISSUE TITLE
Check whether HttpProxyWithSpiderArgsMiddleware is needed

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-scrape#296]
~~My understanding is that Scrapy's [HttpProxyMiddleware](https://docs.scrapy.org/en/latest/topics/downloader-middleware.html#module-scrapy.downloadermiddlewares.httpproxy) is [enabled by default](https://docs.scrapy.org/en/latest/topics/downloader-middleware.html#httpproxy-enabled), so we don't need `HttpProxyWithSpiderArgsMiddleware`.~~

* [x] If we close #293, then we can also remove `spider.proxies` in `paraguay_base.py`.

* [x] In PR #271, I make the `http_proxy` and `https_proxy` spider arguments easier to access. If we end up removing `HttpProxyWithSpiderArgsMiddleware`, we can remove these, too.

**Comment by jpmckinney** [comment]
Ah, nevermind – `HttpProxyMiddleware` looks for environment variables (using Python's `urllib.request.getproxies()`), whereas we want to be able to opt-in to proxies per crawl.

That said, could you instead subclass `HttpProxyMiddleware` ([source code](https://github.com/scrapy/scrapy/blob/1.8/scrapy/downloadermiddlewares/httpproxy.py)) and, in its `__init__`, call super and then update `self.proxies` based on spider arguments?

**Comment by jpmckinney** [comment]
A better idea: We can set the environment variables (in the deploy repo), but set `HTTPPROXY_ENABLED` to `False` in `settings.py`. Then, we can just override that setting with `-d setting=HTTPPROXY_ENABLED=True` when scheduling a crawl.

That way, we won't need `HttpProxyWithSpiderArgsMiddleware`, and we can just use the regular middleware. This also means we won't have to do https://github.com/open-contracting/deploy/issues/101

**Comment by romifz** [comment]
Sounds good for me.

**Comment by jpmckinney** [comment]
For the configuration changes, I think I just have to edit `supervisor.conf` in the deploy repo, and `settings.py` here.
