### ISSUE TITLE
Update Response body as unicode

### ISSUE THREAD

**Issue by aguilerapy** [open-contracting/kingfisher-scrape#302]
[Scrapy](https://docs.scrapy.org/en/latest/index.html) recommends using the [text](https://docs.scrapy.org/en/latest/topics/request-response.html#scrapy.http.TextResponse.text) attribute instead of the [body_as_unicode()](https://docs.scrapy.org/en/latest/topics/request-response.html#scrapy.http.TextResponse.body_as_unicode) method for response objects. This method is kept only for backward compatibility.

For example, use `json_data = json.loads(response.text)` instead of `json_data = json.loads(response.body_as_unicode())`

This affects many scrapers.

**Comment by aguilerapy** [comment]
Scrapers:

- [ ] afghanistan_records
- [ ] afghanistan_releases
- [ ] armenia
- [ ] australia
- [ ] australia_nsw
- [ ] buenos_aires
- [ ] canada_montreal
- [ ] chile_base
- [ ] colombia
- [ ] georgia_records
- [ ] georgia_releases
- [ ] honduras_portal_records
- [ ] honduras_portal_releases
- [ ] indonesia_bandung
- [ ] kenya_makueni
- [ ] mexico_administracion_publica_federal
- [ ] mexico_cdmx
- [ ] mexico_inai
- [ ] mexico_jalisco
- [ ] moldova
- [ ] moldova_records
- [ ] moldova_releases
- [ ] nepal_portal
- [ ] nigeria_portal
- [ ] paraguay_base
- [ ] paraguay_hacienda
- [ ] portugal
- [ ] quien_es_quien
- [ ] uganda_releases
- [ ] uk_contracts_finder
- [ ] uk_fts
- [ ] uruguay_base
- [ ] zambia

**Comment by jpmckinney** [comment]
Feel free to do a big regex-replace, since this is a lot of files :)
