### ISSUE TITLE
Remove instruction to install scrapyd-client 

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher-scrape#31]
As well as requirements.txt, it would be good to have requirements.in. Can people remember what key packages should be in there?

(I'm also curious to see if we can put the contents of requirements.in into setup.py, and to see if that will solve a problem with scrapyd deployment)

The same is also true for  	requirements_scrapycloud.txt ?

**Comment by odscjames** [comment]
When we do this, note that the comments in scrapy/settings.py MIGHT be for a different version of scrapy* - try and make sure they match the version we use

* We have seen different default values in the comments in settings and in the docs

**Comment by odscjames** [comment]
If pull request is merged in, then we already have scrapyd-client so maybe the docs in https://kingfisher-scrape.readthedocs.io/en/latest/use-scrapyd.html need updating

**Comment by jpmckinney** [comment]
Updated title to be about last remaining issue.
