### ISSUE TITLE
Use save_response_to_disk instead of save_data_to_disk where possible

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-scrape#328]
I think it's possible in:

* [x] kenya_makueni
* [x] nepal_dhangadhi
* [x] nepal_portal
* [x] nigeria_portal
* [x] uganda_releases
* [x] uruguay_base

**Comment by aguilerapy** [comment]
Uganda API could return the package with empty release list, anyway I saved it.
