### ISSUE TITLE
Make sure TECHNICAL-DECISIONS.md is written into docs/

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher-scrape#44]
(Whatever is still appropriate, at least)

https://github.com/open-contracting/kingfisher/blob/e8c9c440f2029960480e0d3b7e78dfa4240295d9/TECHNICAL-DECISIONS.md

**Comment by jpmckinney** [comment]
I don't see anything that isn't standard practice / in the handbook / obvious from looking at the code, so closing.
