### ISSUE TITLE
Don't store local files named with a MD5

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher-scrape#45]
Currently we store local files as a hash as a name, https://github.com/open-contracting/kingfisher-scrape/blob/master/kingfisher_scrapy/pipelines.py#L35

I think it would be good if we could find a way back to the old system, where most of the time names were stored as something meaningful. It would help people looking back at things later to track what went on and might help with debugging too.

**Comment by odscjames** [comment]
Turns out this is not easy as file_path function does not have a way to see the info dict. I need to look into the Scrapy workflow a bit more.

**Comment by odscjames** [comment]
New pipeline solves this! Now we just have to get all scrapers to use it ...

**Comment by jpmckinney** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Views: Several queries use deprecated fields instead of parties array](https://trello.com/c/sw1TVcsP/177-views-several-queries-use-deprecated-fields-instead-of-parties-array)
