### ISSUE TITLE
After run finished, send finish to new end end point

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher-scrape#57]
https://kingfisher-process.readthedocs.io/en/latest/web-api-v1.html#end-collection-store

@rhiaro you said there was way to have a custom callback at the end I think - do you know what it is off the top of your head? No worries if not, I'll google it.

**Comment by rhiaro** [comment]
I think you want the [https://doc.scrapy.org/en/latest/topics/signals.html#topics-signals](spider_closed signal)

**Comment by odscjames** [comment]
Note after #87 is merged, there is one more scraper to do - it extends the XML Scraper!
