### ISSUE TITLE
Port Ukraine scraper

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher-scrape#60]
https://github.com/open-contracting/kingfisher-scrape/blob/master/ocdskingfisher/sources/ukraine.py

**Comment by jpmckinney** [comment]
Note that the old scraper has not been tested according to open-contracting/kingfisher#100

**Comment by romifz** [comment]
Ukraine's endpoint is not working at the moment: http://ocds.prozorro.openprocurement.io/

**Comment by jpmckinney** [comment]
I don't think this is coming back anytime soon. I'll create a new issue about deleting the old `ocdskingfisher`.
