### ISSUE TITLE
Port Moldova scraper (old website)

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher-scrape#66]
https://github.com/open-contracting/kingfisher-scrape/blob/master/ocdskingfisher/sources/moldova.py

**Comment by jpmckinney** [comment]
Please address this comment when working on this issue: https://github.com/open-contracting/kingfisher/issues/100#issuecomment-445547759

**Comment by jpmckinney** [comment]
Note that the old scraper has not been tested according to open-contracting/kingfisher#100

**Comment by odscjames** [comment]
Now we have a totally new Moldova API so the comment  @jpmckinney links to isn't relevant any more.

**Comment by jpmckinney** [comment]
We might still want to port the older Moldova source at http://opencontracting.date.gov.md for which there is an old-Kingfisher source. However, this is low priority as it is not being updated, AFAIK.
