### ISSUE TITLE
Port mexico_inai scraper

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher-scrape#68]
https://github.com/open-contracting/kingfisher-scrape/blob/master/ocdskingfisher/sources/mexico_inai.py

**Comment by jpmckinney** [comment]
As part of this, review comments in https://github.com/open-contracting/kingfisher/issues/190

**Comment by jpmckinney** [comment]
@odscjames Closed by #187?

**Comment by odscjames** [comment]
Yes
