### ISSUE TITLE
Port mexico_administracion_publica_federal scraper

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher-scrape#71]
https://github.com/open-contracting/kingfisher-scrape/blob/master/ocdskingfisher/sources/mexico_administracion_publica_federal.py

**Comment by jpmckinney** [comment]
As part of this, review comments in https://github.com/open-contracting/kingfisher/issues/190

**Comment by jpmckinney** [comment]
Blocked as https://api.datos.gob.mx/v1/contratacionesabiertas isn't returning data.

**Comment by odscjames** [comment]
Seems to return results now.

**Comment by jpmckinney** [comment]
@odscjames Closed by #189?

**Comment by odscjames** [comment]
Yes
