### ISSUE TITLE
Port australia Scraper

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher-scrape#77]

**Comment by jpmckinney** [comment]
Note that the old scraper has not been tested according to open-contracting/kingfisher#100

**Comment by yolile** [comment]
It seems that this is actually done: https://github.com/open-contracting/kingfisher-scrape/blob/master/kingfisher_scrapy/spiders/australia_nsw.py

**Comment by jpmckinney** [comment]
I think this is for the federal level, not New South Wales.
