### ISSUE TITLE
[1.1] Install Memorious / Scrapy on a dev server, set up and configured to talk to the API from #263 with the 2-3 scrapers from #262

### ISSUE THREAD

**Issue by robredpath** [open-contracting/kingfisher-scrape#80]
- All config should be in Salt

**Comment by jpmckinney** [comment]
@robredpath Pinging again.

**Comment by jpmckinney** [comment]
@robredpath @rhiaro @odscjames We have [three `266-posttoapi` branches]((https://github.com/open-contracting/kingfisher-scrape/branches/all). Do any of them need to be integrated, or can they all be deleted?

**Comment by rhiaro** [comment]
Yep, deleted.

**Comment by odscjames** [comment]
I think this issue can be closed; the main task it was for has been accomplished?
