### ISSUE TITLE
Add Georgia scraper

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/kingfisher-scrape#83]
Georgia shared an updated bulk file and links to their releases and records APIs.

I'll share links separately as I don't think these are public yet.

Could we get the updated bulk file loaded into kingfisher early next week (it should be possible to load the local file using the existing scraper)?

I'll also need to provide feedback on the API, so if there was time to try and write a scraper for that (and share feedback on any ways it could be improved) that would be great, otherwise I can have a play with it myself on my machine.

**Comment by jpmckinney** [comment]
Also: Georgia has this older data source: http://opendata.spa.ge/#/tenders (Click English top-left)

When I tried, the "All tenders in zip file" expands 67784 files in annual folders from 2010 to 2017, almost all of which are 0 bytes.

However, the individual JSON links work.

**Comment by jpmckinney** [comment]
@duncandewhurst Do you know if the URL they shared is now considered public? Tagging as 'blocked' in the interim.

**Comment by duncandewhurst** [comment]
They had only shared a private dropbox link if I remember correctly which we local loaded.

However, today they have shared public URLs:
   
* ZIP of release packages at https://odapi.spa.ge/spage.json.zip
* XLSX dump of releases at https://odapi.spa.ge/spage.xlsx
* via OCDS API. OpenAPI definition at https://odapi.spa.ge/api/swagger.json, readable version at https://odapi.spa.ge/api/swagger.ui

Can we get a scraper written as a priority as they have requested feedback on the data.

**Comment by pindec** [comment]
Scraper is done, and run.
