### ISSUE TITLE
Should we always be raising DropItem at the end of the pipeline?

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher-scrape#88]
From #59 - @rhiaro says:

> I think you need to raise `DropItem` regardless of whether the request was successful, otherwise it's going to pass the API response through the pipeline and throw up some more confusing errors

**Comment by jpmckinney** [comment]
I understand this now. I'll work up a PR.

**Comment by jpmckinney** [comment]
https://docs.scrapy.org/en/latest/topics/item-pipeline.html#process_item

> process_item: This method is called for every item pipeline component. process_item() must either: return a dict with data, return an Item (or any descendant class) object, return a Twisted Deferred or raise DropItem exception. Dropped items are no longer processed by further pipeline components.

For our use case, the only option that makes sense is to raise DropItem.

**Comment by jpmckinney** [comment]
Alternately, I'm not 100% sure whether we should just use the `scrapy.signals.item_scraped` signal, instead of an item pipeline.

https://docs.scrapy.org/en/latest/topics/signals.html#scrapy.signals.item_scraped

**Comment by jpmckinney** [comment]
My understanding is that Scrapyd, by default, won't write the items that make it through the item pipeline ([see docs](https://scrapyd.readthedocs.io/en/stable/config.html#items-dir)). So, I think it's fine to just use the signal, as implemented in #274.
