### ISSUE TITLE
Have a list of sources, and the state of each one somewhere

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher-scrape#91]
Maybe automatically generated, or just list in docs like the last one? (That seemed to work - the list doesn't change that often)

**Comment by jpmckinney** [comment]
Should this be in a spreadsheet? I figure we shouldn't have to update the docs in order to update the state of a source.

**Comment by odscjames** [comment]
I guess there are two types of changes we want to document:

  *  Changes to the external API, so something has changed even thought there is no code change. (Examples include a external API going off-line; that scraper is now dead even thought the code hasn't changed.)
  *  Changes to the code (Examples include adding the page parameter, as in #109)

A spreadsheet is good for the first point. A page in the docs like last time is good for the second point, as pull requests reviews can enforce that docs change as the code changes.

I don't know what is best - but it's good to have something, so I'm going to start with a page in the docs as that's what we had before, and that would help with the code we just merged. We can always move the information later, but it's good to just start gathering some info somewhere. I'll leave this ticket open so that discussion isn't forgotten.

**Comment by jpmckinney** [comment]
Presumably closed by #110

**Comment by jpmckinney** [comment]
https://kingfisher-scrape.readthedocs.io/en/latest/sources.html
